from enum import Enum


class SEX(Enum):
    NOT_SPECIFIED = "NOT SPECIFIED"
    FEMALE = "FEMALE"
    MALE = "MALE"


class ONLINE(Enum):
    ONLINE = "ONLINE"
    NOT_ONLINE = "NOT ONLINE"


class RELATION(Enum):
    NOT_SPECIFIED = "NOT SPECIFIED"
    NOT_MARRIED = "NOT MARRIED"
    HAVE_FRIEND = "HAVE FRIEND"
    ENGAGED = "ENGAGED"
    EVERYTHING_IS_COMPLICATED = "EVERYTHING_IS_COMPLICATED"
    ACTIVE_SEARCH = "ACTIVE_SEARCH"
    IN_LOVE = "IN LOVE"
    CIVIL_MARRIAGE = "CIVIL MARRIAGE"




