from enum import Enum


class SchoolType(Enum):
    SCHOOL = "SCHOOL"
    GYMNASIUM = "GYMNASIUM"
    LYCEUM = "LYCEUM"
    BOARDING_SCHOOL = "BOARDING_SCHOOL"
    EVENING_SCHOOL = "EVENING_SCHOOL"
    MUSIC_SCHOOL = "MUSIC_SCHOOL"
    SPORTS_SCHOOL = "SPORTS_SCHOOL"
    ART_SCHOOL = "ART_SCHOOL"
    COLLAGE = "COLLAGE"
    PROFESSIONAL_LYCEUM = "PROFESSIONAL_LYCEUM"
    TECHNICAL_SCHOOL = "TECHNICAL_SCHOOL"
    VOCATIONAL_SCHOOL = "VOCATIONAL_SCHOOL"
    UCHILISHE = "UCHILISHE"
    SCHOOL_OF_ARTS = "SCHOOL_OF_ARTS"


class Sex(Enum):
    NOT_SPECIFIED = "NOT SPECIFIED"
    FEMALE = "FEMALE"
    MALE = "MALE"


class Online(Enum):
    ONLINE = "ONLINE"
    NOT_ONLINE = "NOT ONLINE"


class Relation(Enum):
    NOT_SPECIFIED = "NOT SPECIFIED"
    NOT_MARRIED = "NOT MARRIED"
    HAVE_FRIEND = "HAVE FRIEND"
    ENGAGED = "ENGAGED"
    EVERYTHING_IS_COMPLICATED = "EVERYTHING_IS_COMPLICATED"
    ACTIVE_SEARCH = "ACTIVE_SEARCH"
    IN_LOVE = "IN LOVE"
    CIVIL_MARRIAGE = "CIVIL MARRIAGE"
